---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: "{{ lookup('env', 'RESOURCE_GROUP') }}"
domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"

admin_email: "{{ lookup('env', 'ADMIN_EMAIL') }}"

vmtags:
  StudentId: "{{ lookup('env', 'STUDENTID') }}"

pub_ssh_key_location: "{{ lookup('env', 'PUB_SSH_KEY_LOCATION') }}"

lb_method: least_conn

server_user: "{{ lookup('env', 'SERVER_USER') }}"
server_user_pass: "{{ lookup('env', 'SERVER_USER_PASS') }}"
server_user_groups:
  - sudo
