- name: Start MySQL Container
  docker_container:
    name: db
    image: "mysql:5.7"
    command: "--default-authentication-plugin=mysql_native_password"
    env:
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
    restart_policy: always
    published_ports:
      - "3306:3306"

- name: Start Node Exporter
  docker_container:
    image: prom/node-exporter:v1.2.2
    name: node_exporter
    published_ports:
      - "9100:9100"
    restart_policy: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
