---
- name: Rolling update for Microblog Application
  hosts: appserver
  serial: 1 # Kör en server i taget
    dockerhub_username: "falkendev"
    github_release_tag: "0.2.0"
    ansible_python_interpreter: /usr/bin/python3
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
    - docker-install
  tasks:
    - name: Pull the latest Microblog image based on GitHub release tag
      docker_image:
        name: "{{ dockerhub_username }}/microblog:{{ github_release_tag }}-prod"
        source: pull

    - name: Restart Microblog Container
      docker_container:
        name: microblog
        image: "{{ dockerhub_username }}/microblog:{{ github_release_tag }}-prod"
        env:
          DATABASE_URL: "mysql+pymysql://microblog:password@{{ groups['database'][0] }}:3306/microblog"
        ports:
          - "8000:5000"
        restart_policy: always
        published_ports:
          - "8000:8000"
        state: started

    - name: Wait for the application to start
      wait_for:
        port: 8000
        delay: 10 # Seconds

    - name: Verify the deployment
      uri:
        url: "http://{{ inventory_hostname }}:8000/"
        return_content: yes
        status_code: 200
      register: result

    # - name: Check if correct version is running
    #   assert:
    #     that:
    #       - "'expected_version_string' in result.content" # ändra sen
