---
- hosts:
    - loadbalancer
  pre_tasks:
    - raw: apt-get install -y python-simplejson
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
    - docker-install
    - load_balancer
