name: Bandit, Trivy, and Dockle

on:
  workflow_call:
  release:
    types: [created]

jobs:
  BTD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          pip install bandit
          curl -sfL https://raw.githubusercontent.com/goodwithtech/dockle/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Bandit
        run: make bandit-test

      # - name: Run Trivy
      #   run: trivy-test

      - name: Run Dockle
        run: make dockle-test TAG=${{ github.event.release.tag_name }}-prod
